# Generated by Django 3.2.14 on 2022-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo/')),
                ('offer_line', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
