# Generated by Django 3.2.14 on 2022-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_websiteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
