# Generated by Django 3.2.14 on 2022-08-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220725_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
