# Generated by Django 3.2.14 on 2022-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_homefour'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/HomeSlider/'),
        ),
    ]
