# Generated by Django 3.2.14 on 2022-07-26 10:34

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_1', models.ImageField(upload_to='images/Product/')),
                ('image_2', models.ImageField(upload_to='images/Product/')),
                ('image_3', models.ImageField(upload_to='images/Product/')),
                ('video_link', models.CharField(blank=True, max_length=55, null=True)),
                ('short_Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('login_Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=55, null=True)),
                ('is_best', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
            ],
        ),
    ]
