# Generated by Django 3.2.14 on 2022-07-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video_link',
            new_name='discount_price',
        ),
    ]
