# Generated by Django 3.2.14 on 2022-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_product_is_best_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
