# Generated by Django 3.2.14 on 2022-07-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_short_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='login_Description',
            new_name='long_Description',
        ),
    ]
