# Generated by Django 3.2.14 on 2022-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reivew_msg',
            new_name='review',
        ),
    ]
