# Generated by Django 3.2.14 on 2022-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_rename_reivew_msg_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
