# Generated by Django 3.2.14 on 2022-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
