# Generated by Django 3.2.14 on 2022-07-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_product_card_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card_added',
        ),
    ]
