# Generated by Django 3.2.14 on 2022-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
