# Generated by Django 3.2.14 on 2022-08-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
